name: Auto Build

on:
  push:
    tags:
      - 'alpha*'
      - 'beta*'
      - 'v*'

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: |
          cargo build --release

      - name: Rename binary
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            mv target/release/pipe.exe pipe-windows-amd64.exe
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            cp target/release/pipe pipe-macos-amd64
          else
            cp target/release/pipe pipe-linux-amd64
          fi
        shell: bash

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pipe-*
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
