name: Auto Build + Release

on:
  push:
    tags:
      - 'alpha*'
      - 'beta*'
      - 'v*'

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable

      - name: Build & Install Binary
        shell: bash
        run: |
          cargo install --path . --root dist
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            mv dist/bin/pipe.exe pipe-windows-amd64.exe
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            cp dist/bin/pipe pipe-macos-amd64
          else
            cp dist/bin/pipe pipe-linux-amd64
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pipe-${{ runner.os }}
          path: pipe-*

  release:
    name: Upload Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: Flatten Artifact Folder
        run: |
          find ./dist -type f -exec cp {} . \;

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pipe-*
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
