name: Auto Build + Release

on:
  push:
    tags:
      - 'alpha*'
      - 'beta*'
      - 'v*'

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Rename binary
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            mv target/release/pipe.exe pipe-windows-amd64.exe
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            cp target/release/pipe pipe-macos-amd64
          else
            cp target/release/pipe pipe-linux-amd64
          fi
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: pipe-${{ runner.os }}
          path: pipe-*

  release:
    name: Upload release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./dist

      - name: Flatten artifact directory
        run: |
          find ./dist -type f -exec cp {} . \;

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pipe-*
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
